#!/bin/bash

echo "Starting watch..."

while [ true ]; do
	make
	rm -f .~watch
	echo "This file is used by ./dev in order to determine if ./make needs to be called" > .~watch
	OUT=$(watch -g -c -n 0.1 "find ./ -newer .~watch | grep 'Makefile\|\.[ch]\|\.conf'")
done